<?php

/**
 * BaseEntityFrequency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mining_id
 * @property integer $entity_id
 * @property string $entity_name
 * @property string $entity_type
 * @property integer $bicluster_count
 * @property Mining $Mining
 * 
 * @method integer         getMiningId()        Returns the current record's "mining_id" value
 * @method integer         getEntityId()        Returns the current record's "entity_id" value
 * @method string          getEntityName()      Returns the current record's "entity_name" value
 * @method string          getEntityType()      Returns the current record's "entity_type" value
 * @method integer         getBiclusterCount()  Returns the current record's "bicluster_count" value
 * @method Mining          getMining()          Returns the current record's "Mining" value
 * @method EntityFrequency setMiningId()        Sets the current record's "mining_id" value
 * @method EntityFrequency setEntityId()        Sets the current record's "entity_id" value
 * @method EntityFrequency setEntityName()      Sets the current record's "entity_name" value
 * @method EntityFrequency setEntityType()      Sets the current record's "entity_type" value
 * @method EntityFrequency setBiclusterCount()  Sets the current record's "bicluster_count" value
 * @method EntityFrequency setMining()          Sets the current record's "Mining" value
 * 
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntityFrequency extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_frequency');
        $this->hasColumn('mining_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('entity_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('entity_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('entity_type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('bicluster_count', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('entity', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mining', array(
             'local' => 'mining_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}