<?php

/**
 * BaseChainingLinkType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $chaining_id
 * @property string $name
 * @property integer $status_code
 * @property datetime $start_time
 * @property datetime $end_time
 * @property Chaining $Chaining
 * @property Doctrine_Collection $Links
 * 
 * @method integer             getChainingId()  Returns the current record's "chaining_id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method integer             getStatusCode()  Returns the current record's "status_code" value
 * @method datetime            getStartTime()   Returns the current record's "start_time" value
 * @method datetime            getEndTime()     Returns the current record's "end_time" value
 * @method Chaining            getChaining()    Returns the current record's "Chaining" value
 * @method Doctrine_Collection getLinks()       Returns the current record's "Links" collection
 * @method ChainingLinkType    setChainingId()  Sets the current record's "chaining_id" value
 * @method ChainingLinkType    setName()        Sets the current record's "name" value
 * @method ChainingLinkType    setStatusCode()  Sets the current record's "status_code" value
 * @method ChainingLinkType    setStartTime()   Sets the current record's "start_time" value
 * @method ChainingLinkType    setEndTime()     Sets the current record's "end_time" value
 * @method ChainingLinkType    setChaining()    Sets the current record's "Chaining" value
 * @method ChainingLinkType    setLinks()       Sets the current record's "Links" collection
 * 
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChainingLinkType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chaining_link_type');
        $this->hasColumn('chaining_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('status_code', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('start_time', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('end_time', 'datetime', null, array(
             'type' => 'datetime',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Chaining', array(
             'local' => 'chaining_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ChainingLink as Links', array(
             'local' => 'id',
             'foreign' => 'chaining_link_type_id'));
    }
}