<?php

/**
 * BaseMiningBiClusterCol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bicluster_id
 * @property integer $col_id
 * @property MiningBiCluster $MiningBiCluster
 * 
 * @method integer            getBiclusterId()     Returns the current record's "bicluster_id" value
 * @method integer            getColId()           Returns the current record's "col_id" value
 * @method MiningBiCluster    getMiningBiCluster() Returns the current record's "MiningBiCluster" value
 * @method MiningBiClusterCol setBiclusterId()     Sets the current record's "bicluster_id" value
 * @method MiningBiClusterCol setColId()           Sets the current record's "col_id" value
 * @method MiningBiClusterCol setMiningBiCluster() Sets the current record's "MiningBiCluster" value
 * 
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMiningBiClusterCol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mining_bi_cluster_col');
        $this->hasColumn('bicluster_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('col_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MiningBiCluster', array(
             'local' => 'bicluster_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}