<?php

/**
 * BaseMiningBiCluster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mining_id
 * @property integer $config_id
 * @property Mining $Mining
 * @property ProjectConfig $ProjectConfig
 * @property Doctrine_Collection $Rows
 * @property Doctrine_Collection $Cols
 * @property Doctrine_Collection $TargetChainLinks
 * @property Doctrine_Collection $DestinationChainLinks
 * @property Doctrine_Collection $DocumentLinks
 * 
 * @method integer             getMiningId()              Returns the current record's "mining_id" value
 * @method integer             getConfigId()              Returns the current record's "config_id" value
 * @method Mining              getMining()                Returns the current record's "Mining" value
 * @method ProjectConfig       getProjectConfig()         Returns the current record's "ProjectConfig" value
 * @method Doctrine_Collection getRows()                  Returns the current record's "Rows" collection
 * @method Doctrine_Collection getCols()                  Returns the current record's "Cols" collection
 * @method Doctrine_Collection getTargetChainLinks()      Returns the current record's "TargetChainLinks" collection
 * @method Doctrine_Collection getDestinationChainLinks() Returns the current record's "DestinationChainLinks" collection
 * @method Doctrine_Collection getDocumentLinks()         Returns the current record's "DocumentLinks" collection
 * @method MiningBiCluster     setMiningId()              Sets the current record's "mining_id" value
 * @method MiningBiCluster     setConfigId()              Sets the current record's "config_id" value
 * @method MiningBiCluster     setMining()                Sets the current record's "Mining" value
 * @method MiningBiCluster     setProjectConfig()         Sets the current record's "ProjectConfig" value
 * @method MiningBiCluster     setRows()                  Sets the current record's "Rows" collection
 * @method MiningBiCluster     setCols()                  Sets the current record's "Cols" collection
 * @method MiningBiCluster     setTargetChainLinks()      Sets the current record's "TargetChainLinks" collection
 * @method MiningBiCluster     setDestinationChainLinks() Sets the current record's "DestinationChainLinks" collection
 * @method MiningBiCluster     setDocumentLinks()         Sets the current record's "DocumentLinks" collection
 * 
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMiningBiCluster extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mining_bi_cluster');
        $this->hasColumn('mining_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('config_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mining', array(
             'local' => 'mining_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ProjectConfig', array(
             'local' => 'config_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('MiningBiClusterRow as Rows', array(
             'local' => 'id',
             'foreign' => 'bicluster_id'));

        $this->hasMany('MiningBiClusterCol as Cols', array(
             'local' => 'id',
             'foreign' => 'bicluster_id'));

        $this->hasMany('ChainingLink as TargetChainLinks', array(
             'local' => 'id',
             'foreign' => 'target_bicluster_id'));

        $this->hasMany('ChainingLinkDestination as DestinationChainLinks', array(
             'local' => 'id',
             'foreign' => 'destination_bicluster_id'));

        $this->hasMany('DocumentLink as DocumentLinks', array(
             'local' => 'id',
             'foreign' => 'bicluster_id'));
    }
}