<?php

/**
 * BaseProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property boolean $jigsaw_based
 * @property string $external_database
 * @property Doctrine_Collection $ProjectConfig
 * @property Doctrine_Collection $Minings
 * @property Doctrine_Collection $Visualizations
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method boolean             getJigsawBased()       Returns the current record's "jigsaw_based" value
 * @method string              getExternalDatabase()  Returns the current record's "external_database" value
 * @method Doctrine_Collection getProjectConfig()     Returns the current record's "ProjectConfig" collection
 * @method Doctrine_Collection getMinings()           Returns the current record's "Minings" collection
 * @method Doctrine_Collection getVisualizations()    Returns the current record's "Visualizations" collection
 * @method Project             setName()              Sets the current record's "name" value
 * @method Project             setJigsawBased()       Sets the current record's "jigsaw_based" value
 * @method Project             setExternalDatabase()  Sets the current record's "external_database" value
 * @method Project             setProjectConfig()     Sets the current record's "ProjectConfig" collection
 * @method Project             setMinings()           Sets the current record's "Minings" collection
 * @method Project             setVisualizations()    Sets the current record's "Visualizations" collection
 * 
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('jigsaw_based', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('external_database', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProjectConfig', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $this->hasMany('Mining as Minings', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $this->hasMany('Visualization as Visualizations', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}