<?php

/**
 * BaseMiningJobMapping
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mining_id
 * @property integer $config_id
 * @property integer $status_code
 * @property datetime $start_time
 * @property datetime $end_time
 * @property Mining $Mining
 * @property ProjectConfig $ProjectConfig
 * 
 * @method integer          getMiningId()      Returns the current record's "mining_id" value
 * @method integer          getConfigId()      Returns the current record's "config_id" value
 * @method integer          getStatusCode()    Returns the current record's "status_code" value
 * @method datetime         getStartTime()     Returns the current record's "start_time" value
 * @method datetime         getEndTime()       Returns the current record's "end_time" value
 * @method Mining           getMining()        Returns the current record's "Mining" value
 * @method ProjectConfig    getProjectConfig() Returns the current record's "ProjectConfig" value
 * @method MiningJobMapping setMiningId()      Sets the current record's "mining_id" value
 * @method MiningJobMapping setConfigId()      Sets the current record's "config_id" value
 * @method MiningJobMapping setStatusCode()    Sets the current record's "status_code" value
 * @method MiningJobMapping setStartTime()     Sets the current record's "start_time" value
 * @method MiningJobMapping setEndTime()       Sets the current record's "end_time" value
 * @method MiningJobMapping setMining()        Sets the current record's "Mining" value
 * @method MiningJobMapping setProjectConfig() Sets the current record's "ProjectConfig" value
 * 
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMiningJobMapping extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mining_job_mapping');
        $this->hasColumn('mining_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('config_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status_code', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('start_time', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('end_time', 'datetime', null, array(
             'type' => 'datetime',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mining', array(
             'local' => 'mining_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ProjectConfig', array(
             'local' => 'config_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}