<?php

/**
 * BaseDocumentLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mining_id
 * @property integer $bicluster_id
 * @property integer $document_id
 * @property Mining $Mining
 * @property MiningBiCluster $MiningBiCluster
 * 
 * @method integer         getMiningId()        Returns the current record's "mining_id" value
 * @method integer         getBiclusterId()     Returns the current record's "bicluster_id" value
 * @method integer         getDocumentId()      Returns the current record's "document_id" value
 * @method Mining          getMining()          Returns the current record's "Mining" value
 * @method MiningBiCluster getMiningBiCluster() Returns the current record's "MiningBiCluster" value
 * @method DocumentLink    setMiningId()        Sets the current record's "mining_id" value
 * @method DocumentLink    setBiclusterId()     Sets the current record's "bicluster_id" value
 * @method DocumentLink    setDocumentId()      Sets the current record's "document_id" value
 * @method DocumentLink    setMining()          Sets the current record's "Mining" value
 * @method DocumentLink    setMiningBiCluster() Sets the current record's "MiningBiCluster" value
 * 
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumentLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('document_link');
        $this->hasColumn('mining_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('bicluster_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('document_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mining', array(
             'local' => 'mining_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MiningBiCluster', array(
             'local' => 'bicluster_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}