<?php

/**
 * BaseChaining
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mining_id
 * @property string $name
 * @property string $param
 * @property boolean $configured
 * @property boolean $started
 * @property boolean $complete
 * @property integer $process_id
 * @property Mining $Mining
 * @property Doctrine_Collection $LinkTypes
 * @property Doctrine_Collection $Links
 * @property Doctrine_Collection $Visualizations
 * 
 * @method integer             getMiningId()       Returns the current record's "mining_id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getParam()          Returns the current record's "param" value
 * @method boolean             getConfigured()     Returns the current record's "configured" value
 * @method boolean             getStarted()        Returns the current record's "started" value
 * @method boolean             getComplete()       Returns the current record's "complete" value
 * @method integer             getProcessId()      Returns the current record's "process_id" value
 * @method Mining              getMining()         Returns the current record's "Mining" value
 * @method Doctrine_Collection getLinkTypes()      Returns the current record's "LinkTypes" collection
 * @method Doctrine_Collection getLinks()          Returns the current record's "Links" collection
 * @method Doctrine_Collection getVisualizations() Returns the current record's "Visualizations" collection
 * @method Chaining            setMiningId()       Sets the current record's "mining_id" value
 * @method Chaining            setName()           Sets the current record's "name" value
 * @method Chaining            setParam()          Sets the current record's "param" value
 * @method Chaining            setConfigured()     Sets the current record's "configured" value
 * @method Chaining            setStarted()        Sets the current record's "started" value
 * @method Chaining            setComplete()       Sets the current record's "complete" value
 * @method Chaining            setProcessId()      Sets the current record's "process_id" value
 * @method Chaining            setMining()         Sets the current record's "Mining" value
 * @method Chaining            setLinkTypes()      Sets the current record's "LinkTypes" collection
 * @method Chaining            setLinks()          Sets the current record's "Links" collection
 * @method Chaining            setVisualizations() Sets the current record's "Visualizations" collection
 * 
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChaining extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chaining');
        $this->hasColumn('mining_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('param', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('configured', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('started', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('complete', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('process_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mining', array(
             'local' => 'mining_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ChainingLinkType as LinkTypes', array(
             'local' => 'id',
             'foreign' => 'chaining_id'));

        $this->hasMany('ChainingLink as Links', array(
             'local' => 'id',
             'foreign' => 'chaining_id'));

        $this->hasMany('Visualization as Visualizations', array(
             'local' => 'id',
             'foreign' => 'chaining_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}