<?php

/**
 * BaseVisualization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $mining_id
 * @property integer $chaining_id
 * @property string $name
 * @property clob $jsondata
 * @property Chaining $Chaining
 * @property Mining $Mining
 * @property Project $Project
 * 
 * @method integer       getProjectId()   Returns the current record's "project_id" value
 * @method integer       getMiningId()    Returns the current record's "mining_id" value
 * @method integer       getChainingId()  Returns the current record's "chaining_id" value
 * @method string        getName()        Returns the current record's "name" value
 * @method clob          getJsondata()    Returns the current record's "jsondata" value
 * @method Chaining      getChaining()    Returns the current record's "Chaining" value
 * @method Mining        getMining()      Returns the current record's "Mining" value
 * @method Project       getProject()     Returns the current record's "Project" value
 * @method Visualization setProjectId()   Sets the current record's "project_id" value
 * @method Visualization setMiningId()    Sets the current record's "mining_id" value
 * @method Visualization setChainingId()  Sets the current record's "chaining_id" value
 * @method Visualization setName()        Sets the current record's "name" value
 * @method Visualization setJsondata()    Sets the current record's "jsondata" value
 * @method Visualization setChaining()    Sets the current record's "Chaining" value
 * @method Visualization setMining()      Sets the current record's "Mining" value
 * @method Visualization setProject()     Sets the current record's "Project" value
 * 
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVisualization extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('visualization');
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mining_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('chaining_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('jsondata', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Chaining', array(
             'local' => 'chaining_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Mining', array(
             'local' => 'mining_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}