<?php

/**
 * BaseChainingLinkDestination
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $chaining_link_id
 * @property integer $destination_bicluster_id
 * @property double $distance
 * @property MiningBiCluster $DestinationBiCluster
 * @property ChainingLink $ChainingLink
 * 
 * @method integer                 getChainingLinkId()           Returns the current record's "chaining_link_id" value
 * @method integer                 getDestinationBiclusterId()   Returns the current record's "destination_bicluster_id" value
 * @method double                  getDistance()                 Returns the current record's "distance" value
 * @method MiningBiCluster         getDestinationBiCluster()     Returns the current record's "DestinationBiCluster" value
 * @method ChainingLink            getChainingLink()             Returns the current record's "ChainingLink" value
 * @method ChainingLinkDestination setChainingLinkId()           Sets the current record's "chaining_link_id" value
 * @method ChainingLinkDestination setDestinationBiclusterId()   Sets the current record's "destination_bicluster_id" value
 * @method ChainingLinkDestination setDistance()                 Sets the current record's "distance" value
 * @method ChainingLinkDestination setDestinationBiCluster()     Sets the current record's "DestinationBiCluster" value
 * @method ChainingLinkDestination setChainingLink()             Sets the current record's "ChainingLink" value
 * 
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChainingLinkDestination extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chaining_link_destination');
        $this->hasColumn('chaining_link_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('destination_bicluster_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('distance', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MiningBiCluster as DestinationBiCluster', array(
             'local' => 'destination_bicluster_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ChainingLink', array(
             'local' => 'chaining_link_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}