<?php

/**
 * BaseChainingLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $target_bicluster_id
 * @property integer $chaining_id
 * @property integer $chaining_link_type_id
 * @property MiningBiCluster $TargetBiCluster
 * @property Chaining $Chaining
 * @property ChainingLinkType $ChainingLinkType
 * @property Doctrine_Collection $Destinations
 * 
 * @method integer             getTargetBiclusterId()     Returns the current record's "target_bicluster_id" value
 * @method integer             getChainingId()            Returns the current record's "chaining_id" value
 * @method integer             getChainingLinkTypeId()    Returns the current record's "chaining_link_type_id" value
 * @method MiningBiCluster     getTargetBiCluster()       Returns the current record's "TargetBiCluster" value
 * @method Chaining            getChaining()              Returns the current record's "Chaining" value
 * @method ChainingLinkType    getChainingLinkType()      Returns the current record's "ChainingLinkType" value
 * @method Doctrine_Collection getDestinations()          Returns the current record's "Destinations" collection
 * @method ChainingLink        setTargetBiclusterId()     Sets the current record's "target_bicluster_id" value
 * @method ChainingLink        setChainingId()            Sets the current record's "chaining_id" value
 * @method ChainingLink        setChainingLinkTypeId()    Sets the current record's "chaining_link_type_id" value
 * @method ChainingLink        setTargetBiCluster()       Sets the current record's "TargetBiCluster" value
 * @method ChainingLink        setChaining()              Sets the current record's "Chaining" value
 * @method ChainingLink        setChainingLinkType()      Sets the current record's "ChainingLinkType" value
 * @method ChainingLink        setDestinations()          Sets the current record's "Destinations" collection
 * 
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChainingLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chaining_link');
        $this->hasColumn('target_bicluster_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('chaining_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('chaining_link_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MiningBiCluster as TargetBiCluster', array(
             'local' => 'target_bicluster_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Chaining', array(
             'local' => 'chaining_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ChainingLinkType', array(
             'local' => 'chaining_link_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ChainingLinkDestination as Destinations', array(
             'local' => 'id',
             'foreign' => 'chaining_link_id'));
    }
}