<?php

/**
 * ChainingLinkDestinationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChainingLinkDestinationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChainingLinkDestinationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChainingLinkDestination');
    }
}