<?php

/**
 * Chaining
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Chaining extends BaseChaining {

    /**
     * this will create the link types for this class.
     */
    public function setupLinkTypes() {

        $types = $this->getMining()->getProject()->getUniqueTypes();

        foreach ($types as $result) {
            $link = new ChainingLinkType();
            $link->setChaining($this);
            $link->setName($result[0]);
            $link->save();
        }
    }

    /**
     * Returns parameters as associative array
     * if params aren't in json return empty array
     * @return assoc array
     */
    public function getParams() {
        $json = json_decode($this->getParam(), true);
        return (is_array($json)) ? $json : array();
    }

    /**
     * Takes the parameters associative array and converts it
     * to a text format
     * param1=x, param2=y ...
     * if params aren't in json returns ''.
     * @return string
     */
    public function paramsToString() {
        $str = '';
        $json = $this->getParams();
        if (is_array($json)) {
            foreach ($json as $key => $val) {
                $str .= $key . '=' . $val . ', ';
            }
        }
        return $str;
    }

}
