<?php

/**
 * ChainingLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChainingLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChainingLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChainingLink');
    }
}