<?php

/**
 * ChainingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChainingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChainingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Chaining');
    }
}