<?php

/**
 * DocumentLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DocumentLink extends BaseDocumentLink
{
}
