<?php

/**
 * DocumentLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocumentLink');
    }
}