<?php

/**
 * EntityFrequencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntityFrequencyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntityFrequencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EntityFrequency');
    }
}