<?php

/**
 * MiningBiClusterTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MiningBiClusterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MiningBiClusterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MiningBiCluster');
    }

    /**
     * Find a specific set of Biclusters
     * @param int $mining_id
     * @param int $config_id
     */
    public function findByConfig($mining_id, $config_id) {
        return $this->findBySql('mining_id=? AND config_id=?', array($mining_id, $config_id));
    }
}