<?php

/**
 * MiningTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MiningTable extends Doctrine_Table {
    static public $miningTypes = array(
            '1' => 'BiCluster',
    );

    static public $miningAlgorithms = array(
            '1' => 'Charm',
            '2' => 'LCM',
    );

    /**
     * Return the current types of mining available
     * @return array list of types
     */
    public function getMiningTypes() {
        return self::$miningTypes;
    }

    /**
     * Return the current mining algorithms available
     * @return array list of algorithms
     */
    public function getMiningAlgorithms() {
        return self::$miningAlgorithms;
    }
    /**
     * Returns an instance of this class.
     *
     * @return object MiningTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Mining');
    }
}