<?php

/**
 * MiningBiClusterRowTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MiningBiClusterRowTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MiningBiClusterRowTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MiningBiClusterRow');
    }
}