<?php

/**
 * MiningBiClusterColTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MiningBiClusterColTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MiningBiClusterColTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MiningBiClusterCol');
    }
}