<?php

/**
 * Project
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    MineVis
 * @subpackage model
 * @author     Patrick Fiaux
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Project extends BaseProject {

    public function getConfigMappingsCount() {
        $connection = Doctrine_Manager::connection();
        $query = 'SELECT count(*) AS numOfMappings FROM project_config WHERE project_id=' . $this->getId();
        $statement = $connection->execute($query);
        $statement->execute();
        $resultset = $statement->fetch(PDO::FETCH_OBJ);
        return $resultset->numOfMappings;
    }

    /**
     * Get a list of unique types used in this project...
     * @return array list of types
     */
    public function getUniqueTypes() {
        $connection = Doctrine_Manager::connection();

        //get unique types
        //union can't be done with doctrine...
        $query = "SELECT DISTINCT table_a AS chain_type FROM `project_config` WHERE project_id=" . $this->getId()
                . " UNION "
                . " SELECT DISTINCT table_b AS chain_type FROM `project_config` WHERE project_id=" . $this->getId() . ";";
        $statement = $connection->execute($query);
        $resultset = $statement->fetchAll(Doctrine_Core::FETCH_NUM);
        return $resultset;
    }
}
