<?php

/**
 * ProjectConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectConfig');
    }
}