<?php

/**
 * ProjectTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectTable extends Doctrine_Table {

  //Static until I add upload
  static public $dblist = array(
          'dblp' => 'Dblp Database',
          'imdb' => 'IMDB Database',
          'starwars' => 'Starwars Syntheic Database',
          'yfgdb' => 'Yeast Functional Genomics Database',
          'manpad' => 'Manpad Database',
          'crescent' => 'Crescent Database',
          'vast_atlanticstorm' => 'Atlantic Storm Database',
          'vast_stegosaurus' => 'Stegosaurus Database',
          'vast_2010' => '2010 Database',
          'vast_vastopolis' => 'Vastopolis Database',
  );

  /**
   * Returns a list of the available databases for projects
   * @return array Database names
   */
  public function getDatabaseList() {
    return self::$dblist;
  }

  /**
   * Returns an instance of this class.
   *
   * @return object ProjectTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Project');
  }

}