<?php

/**
 * VisualizationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VisualizationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VisualizationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Visualization');
    }
}