generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Feature
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          feature
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, complete, updated_at]
      filter:  ~
      form:    
        display:
          "Content": [name, description]
          "Status": [complete]
      edit:    ~
      new:
        title: "Add a feature request"
