<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/18 20:00:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfony',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
